# Generated by Django 3.2.7 on 2021-11-05 13:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacttracing_doctor_doctorsinput_patient_patientinput_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttracing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doctorsinput',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='patientinput',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='add.png', max_length=255, verbose_name='image'),
        ),
    ]
