# Generated by Django 3.2.7 on 2021-11-05 14:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211105_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default=0, max_length=200)),
                ('recomendations', models.CharField(choices=[('wait we will give feedback on installation', 'Wait we will give feedback on installation'), ('sorry our services are not available now', 'Sorry our services are not available now')], default=0, max_length=1000)),
                ('remarks', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='PatientInput',
            new_name='CustomerInput',
        ),
        migrations.RenameModel(
            old_name='ContactTracing',
            new_name='Referral',
        ),
        migrations.DeleteModel(
            name='DoctorsInput',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='Customer', max_length=255, verbose_name='image'),
        ),
    ]
