# Generated by Django 3.2.7 on 2021-11-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211105_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinput',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='customerinput',
            name='Phonenumber',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
