# Generated by Django 3.2.5 on 2021-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211112_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininput',
            name='recomendations',
            field=models.CharField(choices=[('wait we will give feedback on installation', 'Wait we will give feedback on installation'), ('sorry our services are not available now', 'Sorry our services are not available now')], default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='admininput',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='admininput',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default=0, max_length=200),
        ),
    ]
