# Generated by Django 3.2.5 on 2021-11-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211112_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinput',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
    ]
