# Generated by Django 3.2.5 on 2021-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_phonenumber_customerinput_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinput',
            name='location',
            field=models.CharField(blank=True, default='location', max_length=300),
        ),
    ]
